# Generated by Django 5.1.8 on 2025-04-18 00:23

import django_mongodb_backend.fields
import spotify_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255)),
                ('musicians', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=spotify_app.models.Musician), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician_name', models.CharField(max_length=255)),
                ('number_of_follower', models.IntegerField(default=0)),
                ('introduce', models.TextField(blank=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'musicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('musicians', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=spotify_app.models.Musician), blank=True, null=True, size=None)),
                ('songs', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=spotify_app.models.Song), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('song_picture', models.FileField(upload_to='song_pictures/')),
                ('song_file', models.FileField(upload_to='song_files/')),
                ('musicians', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=spotify_app.models.Musician), blank=True, null=True, size=None)),
                ('day_add', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('album', django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model=spotify_app.models.Album, null=True)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
