# Generated by Django 5.1.8 on 2025-05-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='musician',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='playlist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
