# Generated by Django 5.1.8 on 2025-05-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_alter_account_table_alter_album_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='admin_account',
        ),
    ]
